# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 722fc007a98409d58b04a958541e23f2b680d7853a2351d39b19f370bd1502db0da16197d204e0511edca0870db615c3cfe6db637c2993ebf7d59fce771047eb

test:
  secret_key_base: 7151b4239fff3d9c8c316482b11a881ad1ff0a9c7006da66ea232624f2f44ce9908f1e8d43ceb732798eac2a83734e8b732ab91a5563cad6bd1071c4434549be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
